---

- hosts: dummies
  vars_prompt: 
      - name: "branch" 
        prompt: "Enter IARC-2019 branch to grab." 
        private: no 
  tasks:
    - apt:
        name: git
    - name: clone a branch of the MST-MRR repository
      git:
        repo: https://github.com/MST-MRR/IARC-2019.git
        dest: /root/IARC-2019
        version: "{{ branch }}"

    - pip:
        requirements: /root/IARC-2019/requirements.txt

    - name: Run a script with arguments
      command: python2 /root/IARC-2019/flight.py -d
